### ISSUE TITLE
General TODO for update plan

### ISSUE THREAD

**Issue by pMononoke** [pMononoke/Doctors#4]
## Entity & Repository
- [ ] @Gedmo Annotation.

- [ ] Convert all DateTime properties to DateTimeImmutable 

- [ ] Change message string (validation|error) from franch to Eng or Ita.

- [ ] Change ORM configuration from Annotation to XML.

- [ ] ?Maybe logical Separation READ/WRITE  

- [ ] Remove User entity (old FOSUserBundle)

## Security & User
- [ ] Configure security bundle

- [ ] Create Security user
